name: Build and Push Docker Images

on:
  push:
    branches: [ main, develop, master ]  # Add your branch names here
  pull_request:
    branches: [ main, develop, master ]

env:
  DOCKER_HUB_USERNAME: abidhasan83  # Your Docker Hub username

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Extract metadata for backend
      id: meta-backend
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_HUB_USERNAME }}/agrolink-backend
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix=sha-
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Extract metadata for mobile
      id: meta-mobile
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_HUB_USERNAME }}/agrolink-mobile
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix=sha-
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ steps.meta-backend.outputs.tags }}
        labels: ${{ steps.meta-backend.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Build and push mobile image
      uses: docker/build-push-action@v5
      with:
        context: ./mobile
        file: ./mobile/Dockerfile
        push: true
        tags: ${{ steps.meta-mobile.outputs.tags }}
        labels: ${{ steps.meta-mobile.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Optional: Update docker-compose.yml with new image tags
  update-compose:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only run on main branch
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Update docker-compose.yml
      run: |
        # Update image tags in docker-compose.yml to use SHA-based tags for production
        SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
        sed -i "s|abidhasan83/agrolink-backend:latest|abidhasan83/agrolink-backend:sha-$SHA_SHORT|g" docker-compose.yml
        sed -i "s|abidhasan83/agrolink-mobile:latest|abidhasan83/agrolink-mobile:sha-$SHA_SHORT|g" docker-compose.yml
        
    - name: Commit updated docker-compose.yml
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docker-compose.yml
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update docker-compose.yml with new image tags [skip ci]"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
